ClientEvents.lang('en_us', event => {
	event.add('gem_class.magic_item', 'Magic Item')
	event.add('loot_category.your_namespace.irons_magic_staff', 'Magic Staff')
	event.add('loot_category.your_namespace.irons_magic_staff.plural', 'Magic Staff')
	event.add('loot_category.your_namespace.spellbook', 'Spellbook')
	event.add('loot_category.your_namespace.spellbook.plural', 'Spellbook')
	event.add('affix.your_namespace:fallback_name', 'Affixed')
	event.add('affix.your_namespace:fallback_name.suffix', 'of Affix')
	event.add('affix.your_namespace:magic_item/attribute/spellpower', 'Powerful')
	event.add('affix.your_namespace:magic_item/attribute/spell_power.suffix', 'of Power')
	event.add('affix.your_namespace:magic_item/attribute/ex_spell_power', 'Transcended')
	event.add('affix.your_namespace:magic_item/attribute/ex_spell_power.suffix', 'of the Juggernaut')
	event.add('affix.your_namespace:magic_item/attribute/mana', 'Mana')
	event.add('affix.your_namespace:magic_item/attribute/mana.suffix', 'of Intelligence')
	event.add('affix.your_namespace:magic_item/attribute/cast_time_reduction', 'Chanting')
	event.add('affix.your_namespace:magic_item/attribute/cast_time_reduction.suffix', 'of le Chant')
	event.add('affix.your_namespace:magic_item/attribute/evocation/ex_evocation_spell_power', 'Invoking')
	event.add('affix.your_namespace:magic_item/attribute/evocation/ex_evocation_spell_power.suffix', 'of the Invoker')
	event.add('affix.your_namespace:magic_item/attribute/evocation/evocation_spell_power', 'Evoking')
	event.add('affix.your_namespace:magic_item/attribute/evocation/evocation_spell_power.suffix', 'of the Evoker')
	event.add('affix.your_namespace:magic_item/attribute/fire/ex_fire_spell_power', 'En-Scorching')
	event.add('affix.your_namespace:magic_item/attribute/fire/ex_fire_spell_power.suffix', 'of the Embers')
	event.add('affix.your_namespace:magic_item/attribute/fire/fire_spell_power', 'Igniting')
	event.add('affix.your_namespace:magic_item/attribute/fire/fire_spell_power.suffix', 'of the Roaster')
	event.add('affix.your_namespace:magic_item/attribute/blood/ex_blood_spell_power', 'Bloodylake')
	event.add('affix.your_namespace:magic_item/attribute/blood/ex_blood_spell_power.suffix', 'of the Blood-Drainer')
	event.add('affix.your_namespace:magic_item/attribute/blood/blood_spell_power', 'Red-Stained')
	event.add('affix.your_namespace:magic_item/attribute/blood/blood_spell_power.suffix', 'of the Blood')
	event.add('affix.your_namespace:magic_item/attribute/holy/holy_spell_power', 'Sanctified')
	event.add('affix.your_namespace:magic_item/attribute/holy/holy_spell_power.suffix', 'of Sanctuary')
	event.add('affix.your_namespace:magic_item/attribute/holy/ex_holy_spell_power', 'Sant')
	event.add('affix.your_namespace:magic_item/attribute/holy/ex_holy_spell_power.suffix', 'of Sacredness')
	event.add('affix.your_namespace:magic_item/attribute/ice/ex_ice_spell_power', 'Glacial')
	event.add('affix.your_namespace:magic_item/attribute/ice/ex_ice_spell_power.suffix', 'of the Iceberg')
	event.add('affix.your_namespace:magic_item/attribute/ice/ice_spell_power', 'Frost')
	event.add('affix.your_namespace:magic_item/attribute/ice/ice_spell_power.suffix', 'of the Icy')
	event.add('affix.your_namespace:magic_item/attribute/eldritch/ex_eldritch_spell_power', 'Ancient')
	event.add('affix.your_namespace:magic_item/attribute/eldritch/ex_eldritch_spell_power.suffix', 'of the Farlander')
	event.add('affix.your_namespace:magic_item/attribute/eldritch/eldritch_spell_power', 'Aberration')
	event.add('affix.your_namespace:magic_item/attribute/eldritch/eldritch_spell_power.suffix', 'of Stranger')
	event.add('affix.your_namespace:magic_item/attribute/lightning/ex_lightning_spell_power', 'Kerauno')
	event.add('affix.your_namespace:magic_item/attribute/lightning/ex_lightning_spell_power.suffix', 'of the Electron')
	event.add('affix.your_namespace:magic_item/attribute/lightning/lightning_spell_power', 'Sparking')
	event.add('affix.your_namespace:magic_item/attribute/lightning/lightning_spell_power.suffix', 'of the Spark')
	event.add('affix.your_namespace:magic_item/attribute/nature/ex_nature_spell_power', 'Wisp')
	event.add('affix.your_namespace:magic_item/attribute/nature/ex_nature_spell_power.suffix', 'of the Wisp')
	event.add('affix.your_namespace:magic_item/attribute/nature/nature_spell_power', 'Garlanded')
	event.add('affix.your_namespace:magic_item/attribute/nature/nature_spell_power.suffix', 'of Blooming')
	event.add('affix.your_namespace:magic_item/attribute/ender/ender_spell_power', 'Ender')
	event.add('affix.your_namespace:magic_item/attribute/ender/ender_spell_power.suffix', 'of Ender')
	event.add('affix.your_namespace:magic_item/attribute/ender/ex_ender_spell_power', 'Obliteration')
	event.add('affix.your_namespace:magic_item/attribute/ender/ex_ender_spell_power.suffix', 'of the End')
	event.add('affix.your_namespace:armor/attribute/cooldown', 'Quick-Minded')
	event.add('affix.your_namespace:armor/attribute/cooldown.suffix', 'of the Fast-Wit')
	event.add('affix.your_namespace:armor/attribute/spell_power', 'Spellcasting')
	event.add('affix.your_namespace:armor/attribute/spell_power.suffix', 'of the Spellcasting')
	event.add('affix.your_namespace:armor/attribute/spell_resist', 'Spellshieled')
	event.add('affix.your_namespace:sword/attribute/spell_resist.suffix', 'of the Magehunter')
	event.add('affix.your_namespace:sword/attribute/mana_regen', 'Affinity')
	event.add('affix.your_namespace:sword/attribute/mana_regen.suffix', 'of the Mana')
	event.add('affix.your_namespace:sword/attribute/spell_power', 'Spelling')
	event.add('affix.your_namespace:sword/attribute/spell_power.suffix', 'of the Speller')
})
