ClientEvents.lang('en_us', event => {
  event.add('affix.irons_spellbooks:spellbook/attribute/spell_power', 'Powerful')
  event.add('affix.irons_spellbooks:spellbook/attribute/spell_power.suffix', 'of Power')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_spell_power', 'Transcended')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_spell_power.suffix', 'of the Juggernaut')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_blood_spell_power', 'Bloodylake')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_blood_spell_power.suffix', 'of the Blood-Drainer')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_ender_spell_power', 'Obliteration')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_ender_spell_power.suffix', 'of the End')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_evocation_spell_power', 'Invoking')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_evocation_spell_power.suffix', 'of the Invoker')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_fire_spell_power', 'En-Scorching')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_fire_spell_power.suffix', 'of the Embers')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_holy_spell_power', 'Sanctified')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_holy_spell_power.suffix', 'of Sanctuary')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_ice_spell_power', 'Glacial')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_ice_spell_power.suffix', 'of the Iceberg')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_lighttning_spell_power', 'Kerauno')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_lighttning_spell_power.suffix', 'of the Electron')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_nature_spell_power', 'Wisp')
  event.add('affix.irons_spellbooks:spellbook/attribute/ex_nature_spell_power.suffix', 'of the Wisp')
  event.add("gem_class.magic_item", "Magic Item")
  event.add("text.apotheosis.category.irons_magic_staff", "Magic Staff")
  event.add("text.apotheosis.category.irons_magic_staff.plural", "Magic Staff")
  event.add("text.apotheosis.category.spellbook", "Spellbook")
  event.add("text.apotheosis.category.spellbook.plural", "Spellbook")
  event.add("text.apotheosis.category.ring", "Ring")
  event.add("text.apotheosis.category.ring.plural", "Ring")
  event.add("text.apotheosis.category.necklace", "Necklace")
  event.add("text.apotheosis.category.necklace.plural", "Necklace")
})